---
- name: Test that we have a UCS host, UCS username, and UCS password
  fail:
    msg: 'Please define the following variables: ucs_hostname, ucs_username and ucs_password.'
  when: ucs_hostname is not defined or ucs_username is not defined or ucs_password is not defined
  vars:
    login_info: &login_info
      hostname: "{{ ucs_hostname }}"
      username: "{{ ucs_username }}"
      password: "{{ ucs_password }}"
    default_org: &default_org
      org_dn: org-root/org-Ansible

- name: Ensure BIOS policy with CDN is enabled.
  ucs_managed_objects:
    <<: *login_info
    objects:
    - module: ucsmsdk.mometa.bios.BiosVProfile
      class: BiosVProfile
      properties:
        parent_mo_or_dn: org-root/org-Ansible
        name: kubam
        descr: KUBAM BIOS Settings
        reboot_on_update: "yes"
      children:
      - module: ucsmsdk.mometa.bios.BiosVfConsistentDeviceNameControl
        class: BiosVfConsistentDeviceNameControl
        properties:
          vp_cdn_control: enabled
        

- name: Configure Server UUID Pools
  ucs_uuid_pool:
    <<: *login_info
    <<: *default_org
    name: Ansible-Pool
    order: sequential
    first_uuid: CAFE-000000000001
    last_uuid:  CAFE-000000000256

- name: Configure Vmedia Policy
  ucs_managed_objects:
    <<: *login_info
    objects:
    - module: ucsmsdk.mometa.cimcvmedia.CimcvmediaMountConfigPolicy
      class: CimcvmediaMountConfigPolicy
      properties: 
        name: kubam-centos7.5
        retry_on_mount_fail: "yes"
        parent_mo_or_dn: org-root/org-Ansible
        descr: "KUBAM policy"
      children:
      - module: ucsmsdk.mometa.cimcvmedia.CimcvmediaConfigMountEntry
        class: CimcvmediaConfigMountEntry
        properties:
          mapping_name: centos7.5
          device_type: cdd
          mount_protocol: http
          remote_ip_address: 10.93.140.118
          image_name_variable: none
          image_file_name: centos7.5-boot.iso
          image_path: kubam
      - module: ucsmsdk.mometa.cimcvmedia.CimcvmediaConfigMountEntry
        class: CimcvmediaConfigMountEntry
        properties:
          mapping_name: ks
          device_type: hdd
          mount_protocol: http
          remote_ip_address: 10.93.140.118
          image_name_variable: service-profile-name
          image_path: kubam

- name: Configure Boot Policy
  ucs_managed_objects:
    <<: *login_info
    objects:
    - module: ucsmsdk.mometa.lsboot.LsbootPolicy
      class: LsbootPolicy
      properties:
        name: kubam
        parent_mo_or_dn: org-root/org-Ansible
        reboot_on_update: "yes"
        enforce_vnic_name: "yes"
        boot_mode: "legacy"
        descr: kubam-boot

- name: Add local disk to boot order
  ucs_managed_objects:
    <<: *login_info
    objects:
    - module: ucsmsdk.mometa.lsboot.LsbootStorage
      class: LsbootStorage
      properties:
        parent_mo_or_dn: "org-root/org-Ansible/boot-policy-kubam"
        order: "1"
      children:
      - module: ucsmsdk.mometa.lsboot.LsbootLocalStorage
        class: LsbootLocalStorage
        properties:
          status: created
        children:
        - module: ucsmsdk.mometa.lsboot.LsbootDefaultLocalImage
          class: LsbootDefaultLocalImage
          properties:
            order: "1"
          

- name: Add cimc to boot order.
  ucs_managed_objects:
    <<: *login_info
    objects:
    - module: ucsmsdk.mometa.lsboot.LsbootVirtualMedia
      class: LsbootVirtualMedia
      properties:
        parent_mo_or_dn: "org-root/org-Ansible/boot-policy-kubam"
        order: "2"
        access: "read-only-remote-cimc"
        lun_id: "0"


- name: Add local disk config policy
  ucs_managed_objects:
    <<: *login_info
    objects:
    - module: ucsmsdk.mometa.storage.StorageLocalDiskConfigPolicy
      class: StorageLocalDiskConfigPolicy
      properties:
        parent_mo_or_dn: org-root/org-Ansible
        protect_config: "no"
        name: kubam
        descr: "KUBAM local boot, accept everything"
        flex_flash_raid_reporting_state: disable
        flex_flash_state: disable
        mode: any-configuration

- name: Add scrub policy
  ucs_managed_objects:
    <<: *login_info
    objects:
    - module: ucsmsdk.mometa.compute.ComputeScrubPolicy
      class: ComputeScrubPolicy
      properties:
        parent_mo_or_dn: org-root/org-Ansible
        flex_flash_scrub: "no"
        disk_scrub: "yes"
        name: kubam
        bios_settings_scrub: "no"
        descr: "Destroy data when SP is disassociated."

- name: Ensure Maintenance Policy is correct
  ucs_managed_objects:
    <<: *login_info
    objects:
    - module: ucsmsdk.mometa.lsmaint.LsmaintMaintPolicy
      class: LsmaintMaintPolicy
      properties:
        name: kubam
        parent_mo_or_dn: org-root/org-Ansible
        data_disr: "immediate"
        uptime_disr: "immediate"

- name: Create Service Profile Template
  ucs_service_profile_template:
    <<: *login_info
    <<: *default_org
    name: CentOS
    template_type: updating-template
    uuid_pool: Ansible-Pool
    lan_connectivity_policy: Linux
    vmedia_policy: kubam-centos7.5
    bios_policy: kubam
    boot_policy: kubam
    local_disk_policy: kubam
    scrub_policy: kubam
    maintenance_policy: kubam


